version: '2.4'
services:
  db:
    image: postgres
    container_name: Server
    environment:
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - server_data:/var/lib/postgres
volumes:
  server_data:
